# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


############################################################################
### NOTE! To create azure servers use the following:
### vagrant up --provider=azure
### or
### vagrant up --provider=azure --no-parallel
### To create local virtual servers use the following:
### vagrant up --provider=virtualbox
############################################################################

## Created by Michael Hillström, 2018-11-18


Vagrant.configure('2') do |config|

##############################################################
	### Default settings###
	
	### Configuration for virtual machines
	os = "bento/ubuntu-16.04"
	net_ip = "192.168.50"
	###  

	## For masterless, mount your salt file root
	config.vm.synced_folder "saltstack/salt/", "/srv/salt"
	
	## Create array to hold info about all local virtual machines
	machines = 	[
				["appserver",    "#{net_ip}.11",    "1024",    os ],
				["dbserver",    "#{net_ip}.12",    "1024",    os ],
				]

	## Add test servers to the machines array
#	(1..3).each do |i|	
#		machines.push(["tst#{i-1}",    "#{net_ip}.#{i+13}",    "1024",    os ])
#	end	### i	

##############################################################
	# Configure vm provider -  Virtualbox
	
	machines.each do |vmname,ip,mem,os|
		config.vm.define "#{vmname}" do |minion_config|

			#############################################################
			### VIRTUALBOX ###
			minion_config.vm.provider "virtualbox" do |vb, override|
				override.vm.box = "#{os}"
				vb.memory = "#{mem}"
				vb.cpus = 1
				vb.name = "#{vmname}"			
			end # vb, override

			### AZURE ###
			minion_config.vm.provider "azure" do |azure, override| 
	
				# Specify SSH key - Needed for Azure
				override.ssh.private_key_path = '~/.ssh/key_trsab2k'

				override.vm.synced_folder ".", "/vagrant", disabled: true
#				minion_config.vm.box = 'azure'
				override.vm.box = 'azure'

		
				# Mandatory options
				azure.tenant_id = ENV['AZURE_TENANT_ID']
				azure.client_id = ENV['AZURE_CLIENT_ID']
				azure.client_secret = ENV['AZURE_CLIENT_SECRET']
				azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
		
				# Optional options
#				location = 'westus'
				azure.vm_name = "#{vmname}" "t1st"
				azure.vm_size = 'Standard_A0'
				azure.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'				
			end # azure, override			
			##################################################################
			
			minion_config.vm.hostname = "#{vmname}"
			minion_config.vm.network "private_network", ip: "#{ip}"
			
			
			### PROVISIONING--- Using Saltstack
			minion_config.vm.provision "salt" do |salt|
				salt.minion_config = "saltstack/etc/#{vmname}"
				salt.install_type = "stable"
				salt.masterless = true
				salt.run_highstate = true
				salt.verbose = true
				salt.colorize = true
				salt.bootstrap_options = "-P -c /tmp"
			end	### salt
					
		end # minion_config
	end # machines
	
end	### config
